apiVersion: apps/v1
kind: Deployment
metadata:
  name: pima-diabetes-predictor-app
  namespace: diabetes-predictor
  labels:
    app: pima-diabetes-predictor-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pima-diabetes-predictor-app
  template:
    metadata:
      labels:
        app: pima-diabetes-predictor-app
    spec:
      containers:
      - name: app
        image: pima-diabetes-app:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 5001
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pima-diabetes-predictor-app
  namespace: diabetes-predictor
  labels:
    app: pima-diabetes-predictor-app
spec:
  selector:
    app: pima-diabetes-predictor-app
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  type: LoadBalancer  # This will expose the service externally
---
apiVersion: v1
kind: Service
metadata:
  name: pima-diabetes-predictor-app-nodeport
  namespace: diabetes-predictor
  labels:
    app: pima-diabetes-predictor-app
spec:
  selector:
    app: pima-diabetes-predictor-app
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30001
    protocol: TCP
    name: http
  type: NodePort  # Alternative access method for local development