apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: diabetes-predictor

resources:
- namespace.yaml
- api-deployment.yaml
- app-deployment.yaml

images:
- name: pima-diabetes-api
  newTag: latest
- name: pima-diabetes-app
  newTag: latest

commonLabels:
  project: diabetes-predictor
  version: v1.0.0